FROM python:3.4

RUN \
    wget https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64.deb && \
    dpkg -i dumb-init_*.deb && \
    rm dumb-init_*.deb

COPY requirements.txt /tmp/py-skygear/

# Updated setuptools is required because version updates will cause py-skygear
# to fail because of version string mismatch.
RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir -r /tmp/py-skygear/requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN python setup.py develop
ENV PYTHONUNBUFFERED 0
ENTRYPOINT ["dumb-init"]
