version: '2'

services:
  db:
    image: mdillon/postgis:9.5
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  app:
    image: quay.io/skygeario/skygear-server:canary
    ports:
    - "3000:3000"
    volumes:
    - app_data:/go/src/app/data
    depends_on:
    - db
    command: skygear-server --http
    environment:
      # `db` in the following string should match the name of the database
      # container above.
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      # GOMAXPROCS - The maximum number of Go threads for execution.
      # When unspecified, the default is the number of CPU available, which
      # is the recommended setting.
      #GOMAXPROCS: 1
      PLUGINS: PYTHON
      PYTHON_TRANSPORT: http
      PYTHON_PATH: http://plugin:8000

  plugin:
    build:
      context: .
      dockerfile: Dockerfile-development
    command: py-skygear --http
    volumes:
    - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      PUBSUB_URL: ws://app:3000/pubsub
      SKYGEAR_ADDRESS: tcp://app:5555
      SKYGEAR_ENDPOINT: http://app:3000

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
  app_data:
    driver: local
