# docker-compose.yml

db_data:
  image: mdillon/postgis:9.4
  command: /bin/true

db:
  image: mdillon/postgis:9.4
  volumes_from:
  - db_data
  ports:
  - "5432:5432"

redis_data:
  image: redis:3.0
  command: /bin/true

redis:
  image: redis:3.0
  volumes_from:
  - redis_data

app_data:
  image: quay.io/skygeario/skygear-server:latest
  command: /bin/true

# The Skygear container
app:
  image: quay.io/skygeario/skygear-server:latest
  ports:
  - "3000:3000" # Skygear API Endpoint (HTTP)
  - "5555:5555" # Skygear Plugin Endpoint (ZMQ)
  volumes_from:
  - app_data
  volumes:
  - ./development.ini:/app/development.ini
  links:
  - db
  - redis
  command: skygear-server /app/development.ini
  environment:
    # `db` in the following string should match the name of the database
    # container above.
    DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
    DB_IMPL_NAME: pq
    API_KEY: changeme
    APP_NAME: catapiapp
    PGHOST: db
    PGUSER: postgres
    GODEBUG: netdns=cgo

plugin:
  build: .
  links:
  - app
  - db
  volumes:
  - .:/usr/src/app
  environment:
    DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
    PUBSUB_URL: PUBSUB_URL=ws://app:3000/pubsub
    SKYGEAR_ADDRESS: tcp://app:5555
    SKYGEAR_ENDPOINT: http://app:3000
    SKYGEAR_APIKEY: changeme
    SKYGEAR_APPNAME: catapiapp
